### ISSUE TITLE
Passing `"-x"` or `"--xx"` in arguments

### ISSUE THREAD

**Issue by ethanabrooks** [bkirwi/decline#183] opened 2020-07-14 22:57 UTC
I have a program that takes in strings as arguments and some of those strings may contain flags:

```bash
❯ runs new --name 'Pendulum-v0/maiden' config '--policy SAC --max-time-steps 100000'

Unexpected option: --policy SAC --max-time-steps 100000

Usage: runs new config <config>...

Pass the string of arguments given to launch script as in
 ❯ docker run -d --rm -it <image> <config>

Options and flags:
    --help
        Display this help text.
```
So it appears that decline is parsing `'--policy SAC --max-time-steps 100000''` as an option, not as a string argument. Is there a way to fix this?

By the way I love this library! Wish there was something like this for every language.

**Comment by bkirwi** [comment] 2020-07-17 15:19
Hey, glad to hear you're enjoying the library!

Sad to report that this is the expected behaviour: we stick pretty close to the [GNU / POSIX conventions](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html), and those interpret any argument that starts with a hyphen as an option.

However, we also support the usual `--` escape hatch, which terminates option parsing and treats everything afterwards as a regular argument. So you could invoke your command like so:

```bash
runs new --name 'Pendulum-v0/maiden' config -- '--policy SAC --max-time-steps 100000'
```

An alternative would be to pass the config as a option argument, which is also unambiguous. I don't think we'll be able to support _exactly_ the syntax you're aiming for, though, and still be compliant with the standards...

**Comment by ethanabrooks** [comment] 2020-07-17 17:53
Thanks for the response! The `--` escape hatch would work great but for some reason I'm still having the same issue:
```bash
❯ runs new --name 'Pendulum-v0/maiden' config -- '--policy SAC --max-time-steps 100000'
Unexpected option: --policy SAC --max-time-steps 100000

Usage: runs new config <config>

Pass the string of arguments given to launch script as in
 ❯ <docker-run-command> <image> <config>

Options and flags:
    --help
        Display this help text.
```
Would it help if I provided some minimal code to reproduce?

**Comment by bkirwi** [comment] 2020-07-18 15:48
Huh, yes, that is puzzling. Could plausibly be a bug, but I'd want to see the code before saying for sure. (And my quick attempt to repro didn't find anything.)

And sure - ideal would be to PR a failing test case if you're up for it. The tests that stress the parser are mostly in `ParseSpec`.

**Comment by ethanabrooks** [comment] 2020-07-23 18:56
Ok this still has some vestiges of the original program but it's pretty minimal:
```scala
package runs.manager

import cats.effect.{ExitCode, IO}
import com.monovore.decline.Opts
import com.monovore.decline.effect.CommandIOApp

object Main
    extends CommandIOApp(
      name = "runs",
      header = "Manages long-running processes (runs).",
    ) {

  case class AllOpts(string: String)

  override def main: Opts[IO[ExitCode]] =
    Opts
      .option[String]("string", "a string that may contain flags", short = "s")
      .map(AllOpts)
      .map(_ => IO.pure(ExitCode.Success))
}
```
On the command line:
```bash
❯ sbt "run -- '--num-samples 20'"
[info] Loading settings for project runs-manager-build from plugins.sbt ...
[info] Loading project definition from /home/ethanbro/runs-manager/project
[info] Loading settings for project runs-manager from build.sbt ...
[info] Set current project to runs (in build file:/home/ethanbro/runs-manager/)
[info] Compiling 1 Scala source to /home/ethanbro/runs-manager/target/scala-2.13/classes ...
[info] running runs.manager.Main -- '--num-samples 20'
Unexpected argument: '--num-samples

Usage: runs --string <string>

Manages long-running processes (runs).

Options and flags:
    --help
        Display this help text.
    --string <string>, -s <string>
        a string that may contain flags
2020-07-23 14:51:50,116 shutdown-hooks-run-all ERROR No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
```
In practice, I compile things to a `.deb` using [SBT Native Packager](https://www.scala-sbt.org/sbt-native-packager/index.html) which installs an executable called `runs`. I don't think that should change much, but I do get the same error with that:
```bash
❯ runs -- '--num-samples 20'
Unexpected option: --num-samples 20

Usage: runs --string <string>

Manages long-running processes (runs).

Options and flags:
    --help
        Display this help text.
    --string <string>, -s <string>
        a string that may contain flags
```

**Comment by bkirwi** [comment] 2020-07-24 05:10
Unfortunately `sbt "run -- '--num-samples 20'"` doesn't do what you're hoping due to sbt's arg parsing not matching shell very well. You can see from the different error message: `Unexpected argument: '--num-samples`... note the unbalanced quote.

What happens if you run `sbt 'run -- "--num-samples 20"'`? AFAICT sbt handles that like you'd expect. Locally I'm getting the correct behaviour ("unexpected argument") so if your local behaviour differs that's super interesting. If _that_ works, then that's also pretty weird... possible sbt native packager is changing things somehow?

**Comment by bkirwi** [comment] 2020-07-24 14:20
I now suspect the `--` is getting swallowed by sbt-native-packager's generated start script: https://github.com/sbt/sbt-native-packager/blob/435c15551993f03bb9ae54cefec1957e68d499ab/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template#L183

**Comment by ethanabrooks** [comment] 2020-07-24 17:40
> What happens if you run `sbt 'run -- "--num-samples 20"'`? AFAICT sbt handles that like you'd expect. Locally I'm getting the correct behaviour ("unexpected argument") so if your local behaviour differs that's super interesting. If _that_ works, then that's also pretty weird... possible sbt native packager is changing things somehow?

Works fine:
```bash
❯ sbt 'run -- "--num-samples 20"'
[info] Loading settings for project runs-manager-build from plugins.sbt ...
[info] Loading project definition from /home/ethanbro/runs-manager/project
[info] Loading settings for project runs-manager from build.sbt ...
[info] Set current project to runs (in build file:/home/ethanbro/runs-manager/)
[info] running runs.manager.Main -- "--num-samples 20"
[success] Total time: 1 s, completed Jul 24, 2020, 1:39:33 PM
```

Strangely, the workaround has been to simply put a space at the start of the string: `runs --string ' --num-samples 20'`. It's not really a problem but maybe not as idiomatic as I would like. I guess the thing to do is submit a bug to sbt-native-packager?

**Comment by bkirwi** [comment] 2020-07-24 19:27
> Strangely, the workaround has been to simply put a space at the start of the string: `runs --string ' --num-samples 20'`.

Can see how that would work... the spec is

> Arguments are options if they begin with a hyphen delimiter (‘-’).

and the quoted string (which isn't interpreted by the shell) doesn't start with a `-`, because of the leading space. Definitely not idiomatic though!

And yeah, might be worth opening an issue with sbt-native-packager. My personal opinion would be that the generated script shouldn't be intercepting options on the way to the actual program, because it makes certain CLIs impossible to create using native packager. (Even simple examples like `ls -h` wouldn't work because it's intercepting the help flag.) Using environment variables instead would enable the same customization and remove the corner case bugs. 

Absent that I can see two other workarounds for you:
- Use the custom start script option, and remove the arg processing from sbt-native-packager's start script yourself.
- Using an option instead of a positional argument for the extra flags. So the invocation would look something like: `runs new --name Pendulum-v0/maiden --config '--policy SAC --max-time-steps 100000'`. AFAICT sbt-native-packager will not eat this option so it should behave correctly!

**Comment by bkirwi** [comment] 2022-04-23 17:42
Closing this, since this was a sbt-native-packager bug in the end.

If anyone has followup from the sbt-native-packager end, though, feel free to link that here!

**Closed by bkirwi** 2022-04-23 17:42 UTC
